### ISSUE TITLE
Can't create database with exception_handler gem installed

### ISSUE THREAD

**Issue by agustaf9** [bjorntrondsen/rails_exception_handler#25]
I pulled my project from a repo on a seperate computer and I could not create the database. I get `ActiveRecord::NoDatabaseError: FATAL: "ACM_development" does not exist` and `PG::ConnectionBad: FATAL:  database "ACM_development" does not exist`. 

Removing the excpetion handler gem from my gemfile and running `bundle`, then running `rails db:create` fixes the issue. Then I add the gem back and run `rails db:migrate`.

If ever do `rails db:drop db:create` I get `ExceptionHandler::Error: Migration Required → "errors" doesn't exist`. Their seems to be a circular dependency that makes so a database cannot be created when the exception handler gem is installed.

**Comment by bjorntrondsen** [comment]
I've never seen that issue before and I do db:drop+db:create all the time. No clue what the problem is..
